apiVersion: v1
kind: ConfigMap
metadata:
  name: ubiquity-configmap
data:
   SCBE-DEFAULT-SERVICE: SCBE_DEFAULT_SERVICE_VALUE
   SCBE-MANAGEMENT-IP: SCBE_MANAGEMENT_IP_VALUE
   SCBE-MANAGEMENT-PORT: 8440
   DEFAULT-VOLUME-SIZE: 2
   UBIQUITY-INSTANCE-NAME: UBIQUITY_INSTANCE_NAME_VALUE
   DEFAULT-FSTYPE: ext4 # ext4 or xfs

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ubiquity-deployments-configmap
data:
   LOG-LEVEL: "debug"        # debug / info / error

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: scbe-credentials
data:
   username: "SCBE_USERNAME_VALUE"
   password: "SCBE_PASSWORD_VALUE"

