apiVersion: v1
kind: Service
metadata:
  name: ubiquity
  labels:
    app: ubiquity
spec:
  ports:
    - port: 9999    # If you change this port, you must update the provisioner and the flex with the new port number of ubiquity service.
      protocol: TCP
      targetPort: 9999
  selector:
    app: ubiquity
