apiVersion: v1
kind: Service
metadata:
  name: ubiquity-db
  labels:
    app: ubiquity-db
spec:
  ports:
    - port: 5432  # If you change this port, you must update ubiquity deployment wit the new ubiquity-db port
      protocol: TCP
      targetPort: 5432
  selector:
    app: ubiquity-db
