apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity
    spec:
      containers:
      - name: ubiquity
        image: UBIQUITY_IMAGE
        ports:
        - containerPort: 9999
          name: ubiquity-port
        env:
          # ENV from secret scbe-credentials
          - name: SCBE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: scbe-credentials
                  key: username

          - name: SCBE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: scbe-credentials
                  key: password

          # ENV from ubiquity-configmap
          - name: SCBE_MANAGEMENT_IP
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-MANAGEMENT-IP

          - name: SCBE_MANAGEMENT_PORT
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-MANAGEMENT-PORT

          - name: SCBE_DEFAULT_SERVICE
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-DEFAULT-SERVICE

          - name: DEFAULT_VOLUME_SIZE
              valueFrom:
                configMapKeyRef:
                  name: ubiquity-configmap
                  key: DEFAULT-VOLUME-SIZE

          - name: UBIQUITY_INSTANCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ubiquity-configmap
                  key: UBIQUITY-INSTANCE-NAME

          - name: DEFAULT_FSTYPE    # ext4 or xfs
              valueFrom:
                configMapKeyRef:
                  name: ubiquity-configmap
                  key: DEFAULT-FSTYPE

          # ENV from ubiquity-deployments-configmap
          - name: LOG_LEVEL         # debug / info / error
              valueFrom:
                configMapKeyRef:
                  name: ubiquity-deployments-configmap
                  key: LOG-LEVEL

          - name: LOG_PATH          # Ubiquity log file directory
              valueFrom:
                configMapKeyRef:
                  name: ubiquity-deployments-configmap
                  key: LOG-PATH


          # Env hardcoded for GA v1
          - name: PORT              # Ubiquity port
            value: "9999"
          - name: CONFIG_PATH       # Ubiquity config directory
            value: "/tmp"
          - name: DEFAULT_BACKEND   # or other backends, such as :scbe, spectrum-scale-nfs
            value: "scbe"
          - name: UBIQUITY_DB_PSQL_HOST   # Ubiquity DB hostname
            value: "ubiquity-db"          # the ubiquity-db service name
          - name: UBIQUITY_DB_PSQL_PORT
            value: ""                     # TODO we should specify the default port
          - name: UBIQUITY_DB_CONNECT_TIMEOUT
            value: "3"
#          - name: UBIQUITY_DB_USER   # Ubiquity DB hostname
#            value: "UBIQUITY_DB_USER_VALUE"
#          - name: UBIQUITY_DB_PASSWORD   # Ubiquity DB hostname
#            value: "UBIQUITY_DB_PASSWORD_VALUE"

#        volumeMounts:
#        - mountPath: /container/path/to/certificate    #
#          readOnly: true
#          name: certificates
#
#      volumes:
#      - name: certificates
#        hostPath:
#          path: /host/path/to/certificate  # pub scbe, ubiquity key\dev
#        secret:
#          secretName: mysecret
